networks:
  auth_network:
    driver: bridge
volumes:
  mysql-volume:
    external: true
services:
  database:
    env_file:
      - ./db/.env
    container_name: authentication_db
    hostname: authentication_db
    volumes:
      - mysql-volume:/var/lib/mysql
    build:
      context: ./db
      tags:
        - "auth-db:v1.0.0"
    networks:
      - my_network
    ports:
      - 3306:3306

  frontend:
    env_file:
      - ./authentication_ui/.production.env
    container_name: authentication_ui
    hostname: authentication_ui
    build:
      context: ./authentication_ui
      tags:
        - "auth-ui:v1.0.0"
    networks:
      - my_network
    ports:
      - 5173:5173

  backend:
    env_file:
      - ./authentication_server/.env
    container_name: authentication_server
    hostname: authentication_server
    build:
      context: ./authentication_server
      tags:
        - "auth-api:v1.0.0"
    networks:
      - my_network
    ports:
      - 3000:3000
